version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: culikovo_db
    restart: always
    environment:
      POSTGRES_DB: culikovo_war
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: polinal1
    ports:
      - "5432:5432"
    volumes:
      - ./server/sql_scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    container_name: culikovo_server
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:polinal1@db:5432/culikovo_war
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: